name: Build and Deploy to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: lwknk
          password: dckr_pat_QlUUFryZFfV4xrehz832dxmB3f0

      - name: Build and push Docker image
        run: |
          docker build -t lwknk/weather-caption-app:latest .
          docker push lwknk/weather-caption-app:latest

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App with Azure CLI
        run: |
          az webapp config container set --name weather-caption-123 --resource-group cloud --docker-custom-image-name lwknk/weather-caption-app:latest
          az webapp restart --name weather-caption-123 --resource-group cloud
